name: yes_no_app
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'


dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  #dio: ^4.0.6
  flutter:
    sdk: flutter
  provider: ^6.0.5

dev_dependencies:
  change_app_package_name: ^1.1.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app-icon-512.png"
  min_sdk_android: 21

flutter:

  uses-material-design: true

  assets:
      - assets/

  
  